export const SELECT_MENU = 'SELECT_MENU';
export const SET_OPTION = 'SET_OPTION';
export const TOGGLE_OPTION = 'TOGGLE_OPTION';
export const FETCH_OPTIONS = 'FETCH_OPTIONS';
export const REQUEST_OPTIONS = 'REQUEST_OPTIONS';
export const RECEIVE_OPTIONS = 'RECEIVE_OPTIONS';
export const SAVE_OPTIONS_REQUEST = 'SAVE_OPTIONS_REQUEST';
export const SAVE_OPTIONS_SUCCESS = 'SAVE_OPTIONS_SUCCESS';